name: Deploy HALIFE Website with Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          # Go to project directory
          cd /var/www/halife-website
          
          # Pull latest code
          git pull origin main
          
          # Stop existing containers
          docker-compose down
          
          # Remove old images to save space
          docker image prune -f
          
          # Build and start containers
          docker-compose up -d --build
          
          # Show running containers
          echo "=== Running Containers ==="
          docker ps
          
          # Show logs for debugging
          echo "=== Container Logs ==="
          docker-compose logs --tail=20